blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/lwshakib/sketch-design-with-ai/discussions
    about: Use discussions for questions, ideas, and general chat.
  - name: ðŸ“– Documentation
    url: https://github.com/lwshakib/sketch-design-with-ai/wiki
    about: Check out the wiki for documentation and guides.
